In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [7]:
#1.
"""
list can store elements of the different data type,it is a bulit in data type.

Array can only sotre elements of same data type and it is not a built in data type  for using array in python u have to import numpy module or array module
"""
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>
['1' '2' '3' '4' '5']


In [12]:
#2
#code to print the data type of each and every element of both the variables list_ and array_list.

def func2(lst,arr):
    for i in lst:
        print(f"{i} element of list has type{type(i)}")
    print(" ")
    for i in arr:
        print(f"{i} element of Array has type{type(i)}")

func2(list_,array_list)

1 element of list has type<class 'str'>
2 element of list has type<class 'str'>
3 element of list has type<class 'str'>
4 element of list has type<class 'str'>
5 element of list has type<class 'str'>
 
1 element of Array has type<class 'numpy.str_'>
2 element of Array has type<class 'numpy.str_'>
3 element of Array has type<class 'numpy.str_'>
4 element of Array has type<class 'numpy.str_'>
5 element of Array has type<class 'numpy.str_'>


In [14]:
#3.
array_list = np.array(object = list_, dtype = int)
"""
f each element of list_ is a string and you use dtype=int when converting it into a NumPy array, 
NumPy will attempt to convert each string to an integer.
If the conversion is possible (i.e., the strings represent valid integers),
it will succeed; otherwise, it will raise a ValueError."""

def func3(lst,arr):
    for i in lst:
        print(f"{i} element of list has type{type(i)}")
    print(" ")
    for i in arr:
        print(f"{i} element of Array has type{type(i)}")

func3(list_,array_list)

1 element of list has type<class 'str'>
2 element of list has type<class 'str'>
3 element of list has type<class 'str'>
4 element of list has type<class 'str'>
5 element of list has type<class 'str'>
 
1 element of Array has type<class 'numpy.int64'>
2 element of Array has type<class 'numpy.int64'>
3 element of Array has type<class 'numpy.int64'>
4 element of Array has type<class 'numpy.int64'>
5 element of Array has type<class 'numpy.int64'>


In [20]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
#4
"""
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
"""
print(num_array.shape) #gives u the shape of the array(number of rows and columns)
print(num_array.size) #gives u the  size of the array(number of elements)


(2, 3)
6


In [29]:
#5.
"""
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function."""
arr5=np.zeros((3,3))
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
#6.
"""
Q6. Create an identity matrix of shape (5,5) using numpy functions?"""
arr6=np.ones((5,5))
print(arr6)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
