In [3]:
import numpy as np

In [1]:
#1.
"""
A Python Library is a collection of pre-written codes which we can use to perform tasks without having to write everything from scratch.

Python libraries are very useful as:
.Provides code reusability
.save efforts and time
.enhances efficiency and quality of code.
"""

'\nA Python Library is a collection of pre-written codes which we can use to perform tasks without having to write everything from scratch.\n\nPython libraries are very useful as:\n.Provides code reusability\n.save efforts and time\n.enhances efficiency and quality of code.\n'

In [2]:
#2.
"""Python List is an built-in data type in python You don't have to import any library in order to use python list,
while Numpy Array is only accesible  when you import numpy library to your code.

Numpy Array is faster ,supports element wise operations and can only store same types of data .
while list is slower and can store data of different data types.
"""

"Python List is an built-in data type in python You don't have to import any library in order to use python list,\nwhile Numpy Array is only accesible  when you import numpy library to your code.\n\nNumpy Array is faster ,supports element wise operations and can only store same types of data .\nwhile list is slower and can store data of different data types.\n"

In [64]:
#3.
arr=np.array([
[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]
])

shape=arr.shape
size=arr.size
dim=arr.ndim 
print("The Shape of the given Array is:",shape) #Number of Rows and columns
print("The Size of the given Array is:",size) #Number of elements
print("The Dimension of the given Array is:",dim) #2-D array

The Shape of the given Array is: (3, 4)
The Size of the given Array is: 12
The Dimension of the given Array is: 2


In [65]:
#4
print("Given Array:\n",arr)
print(" ")
print("The first row of the given array is:",arr[0])

Given Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
The first row of the given array is: [1 2 3 4]


In [66]:
#5
"""We can acces the element at the third row and fourth column by using Double-Brackets "[][]"."""

print("Given Array:\n",arr)
print(" ")
print("The element at the third row and fourth column are:",arr[2][3])


Given Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
The element at the third row and fourth column are: 12


In [43]:
#6
#Code to Extract all the indexed elements of the Array
print("Given Array:\n",arr)
print(" ")

def Extract(arr):
    for i in range(arr.shape[0]):      #For rows
        for j in range(arr.shape[1]): #For Columns
            print(arr[i][j],end=" ")

print("All The Elements Are:")
Extract(arr)

Given Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
All The Elements Are:
1 2 3 4 5 6 7 8 9 10 11 12 

In [67]:
#7.

"""We can Create a random 3x3 matrix with values between 0 and 1 using random function of numpy module"""


arr_random=np.random.randint(0,2,(3,3))
print(arr_random)

[[0 0 1]
 [1 1 1]
 [1 0 1]]


In [56]:
#8.
"""
np.random.rand:
Generates random numbers from a uniform distribution between 0 and 1

np.random.randn:
Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1),i.e generate those values whose mean =0 and standard deviation =1"""

'\nnp.random.rand:\nGenerates random numbers from a uniform distribution between 0 and 1\n\nnp.random.randn:\nGenerates random numbers from a standard normal distribution (mean = 0, standard deviation = 1),i.e generate those values whose mean =0 and standard deviation =1'

In [77]:
#9.

"""We can increase the dimension of the given array using np.exand_dims(para1,para2) function."""
print("Given Array:\n",arr)
print(" ")


incrsd_dim=np.expand_dims(arr,axis=0)
print("3-D Array is :\n",incrsd_dim)

Given Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
3-D Array is :
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [82]:
#10.
print("Given Array:\n",arr)   #3 rows and 4 columns
print(" ")       
"""For Transposing this array we can use arr.transpose() function"""

Transposed_array=arr.transpose()  #4 rows and 3 columns
print(Transposed_array)

Given Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [115]:
#11.
Matrix_A= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_B=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Matrix_A:\n",Matrix_A)
print(" ")
print("Matrix_B:\n",Matrix_B)


Mul=Matrix_A*Matrix_B
Add=Matrix_A+Matrix_B
Sub=Matrix_A-Matrix_B
Div=Matrix_B/Matrix_A
print(" ")
print("Element Wise Multiplication:\n",Mul)
print(" ")
#print(" ")
print("Adding Matrix_A and Matrix_B:\n",Add)
print(" ")
print("Subtracting Matrix_B From Matrix_A:\n",Sub)
print(" ")
print("Dividing Matrix_B by Matrix_A:\n",Div)
print(" ")
#For Doing Matrix Multiplication we have to reshape a matrix

Matrix_B=Matrix_B.reshape(4,3)
print("Reshaped Matrix_B:\n",Matrix_B)
print(" ")
Mat_mul=Matrix_A @ Matrix_B
print("Matrix Multiplication:\n",Mat_mul)

Matrix_A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
Matrix_B:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
Element Wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
 
Adding Matrix_A and Matrix_B:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
 
Subtracting Matrix_B From Matrix_A:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
 
Dividing Matrix_B by Matrix_A:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
 
Reshaped Matrix_B:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
 
Matrix Multiplication:
 [[ 70  80  90]
 [158 184 210]
 [246 288 330]]


In [116]:
#12.
"""
arr.byteswap() is used to to swap the byte order of an array i.e used to convert each data into byte format"""


'\narr.byteswap() is used to to swap the byte order of an array i.e used to convert each data into byte format'

In [117]:
#13.
"""
The np.linalg.inv() function in NumPy is used to compute the inverse of a square matrix.

Significance:
Matrix Operations
Solving Linear Equations
Numerical Methods
"""

'\nThe np.linalg.inv() function in NumPy is used to compute the inverse of a square matrix.\n\nSignificance:\nMatrix Operations\nSolving Linear Equations\nNumerical Methods\n'

In [118]:
#14.
"""
The np.reshape() function in NumPy is used to change the shape of an existing array without altering its data. 

It takes two parameters one:array and second-one:(row,column)"""


'\nThe np.reshape() function in NumPy is used to change the shape of an existing array without altering its data. \n\nit takes two parameters one:array and second-one:(row,column)'

In [119]:
#15.
"""
Broadcasting in NumPy is a powerful mechanism that allows for arithmetic operations on arrays of different shapes. 
By following specific rules of shape compatibility"""

'\nBroadcasting in NumPy is a powerful mechanism that allows for arithmetic operations on arrays of different shapes. \nBy following specific rules of shape compatibility'